# Generated by Django 2.2.7 on 2020-01-02 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_auto_20200102_1559'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={'managed': False},
        ),
    ]
